### ISSUE TITLE
Weigh - Default method

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#10]
If the method isn't specified, it feels like it should either have an explicit value of "NotSpecified" or a null value rather than presume how they've been weighed.

**Comment by anitanagaraj** [comment]
Hi Phil, 
I think that is a valid point. We can discuss this today and then close it.

**Comment by cookeac** [comment]
Yes, unless the default is loadcell as that is probably the most common in the industry.

**Comment by anitanagaraj** [comment]
ICAR recommendation is to keep the field as optional and remove the default.
