### ISSUE TITLE
Weigh - Method for feed bin weighers?

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#11]
Provide a weighing method for feed bin weighers such as GrowSafe or OptiWeigh?

**Comment by cookeac** [comment]
Let's discuss at the meeting. If we are weighing the animal with them, are these still working on the same principle as a loadcell/loadbar weighing, or as walkover weighing?

**Comment by cookeac** [comment]
The suggestion from Bill Mitchell at Optiweigh (thanks for the intro, @sejast ) is that these weighers should be categorised differently. The primary reason is that they only weigh the front of the animal and extrapolate this to the entire animal. Other weighers that have a feed bin but use loadbars to weigh the entire animal could just provide "loadcell" weights (with timeOffFeed = 0).

**Comment by cookeac** [comment]
Recommend we add a "frontEndCorrelated" weigh method, based on the descriptions listed in https://www.sciencedirect.com/science/article/abs/pii/S1080744615309773. An alternative would be "partialCorrelated" (based on https://academic.oup.com/jas/article/95/suppl_4/241/4765447) but I think front end correlated will be easier for implementers to recognise and use.

**Comment by anitanagaraj** [comment]
Added.
