### ISSUE TITLE
Score - What is measurement?

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#16]
How is this different from the "score"? Is it in addition to?

**Comment by anitanagaraj** [comment]
Yes this is in addition to score. This is an optional attribute and is applicable to Fat Score, where the measurements at various body sites could be recorded if needed.

**Comment by sushildutt** [comment]
Shall it be called fatScore in that case?

**Comment by cookeac** [comment]
The field Anita is referring to is actually Fat Depth (mm). My preference is that FatScore could be considered a specialised type of score, with the additional attributes of site and optionally fat depth, if that is appropriate.

**Comment by anitanagaraj** [comment]
As discussed in the webinar, this score object is now split into multiple objects specific to Muscle, Fat, Condition and Frame.
