### ISSUE TITLE
Score - scoreType. Should this be traitLabel similar to weigh?

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#17]
That would be more consistent with the weight record.

There may also be values missing from the enumeration, in the case of a processor fat score for instance.

**Comment by cookeac** [comment]
That's a good question and I'm keen we discuss at the meeting.

 A trait label is appropriate where a country or a recording service might have a unique name or identifier for a specific instance of an observation, but the underlying observation itself is the same.
For instance, a birth weight or a mating weight is still a weight.

However, the scores are different types of assessment. In contrast, a condition score at mating or a condition score at weaning are still condition scores, so a trait label could be handy there.

**Comment by cookeac** [comment]
At the meeting we concluded that:
- What scoreType was representing was assessments of different things (not different methods of assessing the same thing). For instance, Condition Score and Frame Score. These should probably be different types of event, perhaps based on a score or assessment base class.

- traitLabel is a way of labelling for example that an event belongs to the same conceptual group for a recording or benchmarking programme. For instance, a Condition Score could be labelled as meaning "post-weaning" or "pre-mating" or "CS24" or whatever else was meaningful.

Therefore we should also add traitLabel to all score events.

**Comment by anitanagaraj** [comment]
Added traitLabel to all score events
