### ISSUE TITLE
Treatment Program should allow for courses and treatments

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#20]
The treatment program is a grouping showing the diagnosis, courses and treatments. In the comment, it says the courses and treatments are 'either or'. We think that it more likely to have both. The courses can act as a plan of what was proposed, while the treatments should be the actuals of what happened.

**Comment by cookeac** [comment]
Yes, I can see that could be possible.
We envisaged these use cases
- a programme is used to plan treatments, but the actual treatments are later recorded as separate events.
- a programme is used to plan or record treatments at the course level and treatments are not recorded individually.
- But it could be possible for a program to contain both a planned course and then actual treatments. This would need a mechanism to identify planned and actual as well.

**Comment by cookeac** [comment]
Agreed we should:
1. Allow both "courses[]" and "treatments[]" in the same programme.
2. Add a planned/actual indicator to courses and treatments.

This would allow you to have a programme that, for instance, contained a planned course, and then actual treatments that implemented that course.

**Comment by anitanagaraj** [comment]
Updated the schema spreadsheet with the changes
