### ISSUE TITLE
Treatment: Courses should support multiple batches or be removed

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#21]
Course is considered as a plan, while the treatment is the actual. The treatment is already recording the batch information. It is feasible that a batch number changes over a course as the same treatment may be applied to many animals. 

If the course is considered like a plan that is created prior to treatment, then the batch numbers may not be known. In this case, there should not be batch number on course.

If the course is supposed to be updated after the treatments, then it will need to support multiple batch numbers.

**Comment by cookeac** [comment]
Course does not necessarily have to be a plan - it could be plan or an actual summary of a course (some vet software doesn't record the individual treatments).

You're right - the batches with batch numbers and expiry dates should be an array for a course.

**Comment by cookeac** [comment]
To make it clear that a course has an array of batch and expiry objects.

**Comment by anitanagaraj** [comment]
Updated in schema spreadsheet.
