### ISSUE TITLE
treatments should refer to diagnosis and courses

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#22]
At the moment, the Treatment Program links diagnosis, courses and treatments. This is a loose grouping which doesn't allow a treatment to link to a particular course or a particular diagnosis (as they both can be an array in the Treatment Program).

The treatment could have an optional property that refers to the course and an array of diagnoses.

**Comment by cookeac** [comment]
I've wondered this too. It could be an optional Reference (based on the icarReferenceType) to a course or diagnosis rather than embedding a diagnosis in a treatment for instance.

**Comment by anitanagaraj** [comment]
Updated in schema spreadsheet
