### ISSUE TITLE
Treatments: Is CourseSummary and CoursePlan different concepts?

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#23]
We need an attribute on course to show if it is a plan or the actual record of treatments (in the case that no Treatments are set). Or we need 2 separate objects.

For example, there is a course planned to do 10 treatments. What does having no treatments mean? Does it mean they did them all or none of them?

It is not explicit what 0 treatments means: they have done all of them or they have done none of them.

**Comment by cookeac** [comment]
Or a course with no treatments could mean that the farm or veterinary software was only capable of recording the course details and not individual treatments. Therefore we do need this attribute.

**Comment by anitanagaraj** [comment]
Added attribute to indicate Plan or Actual
