### ISSUE TITLE
Treatment: Course summary medicine description is unclear

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#24]
The description of medicine in the Course object makes it sound like it is only used for the case that the course is a summary and there are no treatments. In the case that the course is a plan, then the medicine is also useful.

The description can be clear to say this is the medicine used in the course. If the course and summary and plan are split into separate objects (#23), then the medicine should be required for the summary.

**Comment by cookeac** [comment]
Just requires a change to the notes text to clarify.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent , updated in the spreadsheet

**Comment by AndyDe-Aldent** [comment]
Updated the file on my fork.   to get merged with next pull request.
