### ISSUE TITLE
Treatment: withholding needs to consider export

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#26]
How do we differentiate between ESI and meat withholding ?

The body that provided the withholding could be an attribute.

**Comment by cookeac** [comment]
Or ESI could be a separate value in the enumeration? Or maybe it should be a market-specific variant?

**Comment by cookeac** [comment]
At the meeting, three approaches were considered:
1. Add a "market" string field, to allow "domestic", "international", "EU" etc.
2. Add the market to the enumeration e.g. "MeatESI", "MilkEU" - this could get messy.
3. Use a scheme-based approach e.g.  "scheme": "au.gov.apvma.esi" or "au.gov.apvma.whp".

We prefer the latter but are interested in feedback.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent Updated in the spreadsheet -

Attribute added to iscWithdrawalType 
  "market" - string
e.g. data -  domestic, international, EU
description -  Indicates the market the withdrawal applies to

**Comment by AndyDe-Aldent** [comment]
Added the market property to the schema on my fork.

**Comment by cookeac** [comment]
Updated the description of the market property. Added fibre to the product enumeration.
