### ISSUE TITLE
treatments: remove date from Dose

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#27]
Treatment has date applied as part of its core event. The Dose can refer to an amount (with units) without needing the provide date again.

**Comment by Traksewt** [comment]
Maybe Dose is collapsed into Treatment, or Dose is renamed to represent a value with a unit (Measurement). This dose in its current form seems inconsistent with how we discussed weight and embedded objects.

**Comment by cookeac** [comment]
Yes, date should have been removed from Dose prior to publishing the draft.

**Comment by anitanagaraj** [comment]
Updated.

**Comment by Traksewt** [comment]
Good though now Dose Type seems like a generic object of Measurement. If so, this can be reused for weight too.
