### ISSUE TITLE
Treatments: Dose units can follow UN 3 letter standard

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#28]
As discussed for weights, dose should use the same unit format.
"Units specified in UN/CEFACT 3-letter form. ".

**Comment by cookeac** [comment]
I completely agree. @anitanagaraj I'll point you to the UN/CEFACT code list. I felt that the useful subset of these was:

| Abbrev | Name and note |
| -------- | ------------------ |
| MLT | millilitres |
| LTR | litres |
| MGM | milligrams |
| GRM | grams |
| XTU | tube (X prefix as its an ISO 21 packaging unit, as per the ISO 20 recommendation) |
| XVI | vial (X prefix as above) |
| XAR | suppository (X prefix as above) |
| XCQ | cartridge (X prefix as above) |
| GJ | gram per millilitre |
| GL | gram per litre |
| GRN | grain |
| L19 | millilitre per litre |
| NA | milligram per kilogram |
| SYR | syringe (yes, this should have an X but it doesn’t) |
| VP | percent volume |
| WW | volume equal to millilitres of water |

**Comment by anitanagaraj** [comment]
Updated
