### ISSUE TITLE
Treatments: Medicine should include the body the code comes from

### ISSUE THREAD

**Issue by Traksewt** [integritysystemscompany/animal_schema#29]
This is relevant for international products. 

An enum could be a lot to maintain, so text could be fine.

**Comment by cookeac** [comment]
Agree

**Comment by cookeac** [comment]
At the meeting we agreed with this. A new type similar to icarIdentifierType could cover this with a scheme and ID within the scheme. For instance { "scheme": "au.gov.apvma", "id": "12345678" }
