### ISSUE TITLE
Identity and Status - Date fields

### ISSUE THREAD

**Issue by anitanagaraj** [integritysystemscompany/animal_schema#3]
Graham Glover from ABRI suggested having some date fields for status attributes around AI date, animal status date, breed society registration status date, record date , desexed date

**Comment by cookeac** [comment]
Added to **iscAnimalCoreResource.json**:
- breedSocRegDate
- statusChangeDate
- desexedDate
The record date is the *modified* date found in the *meta* property for the animal.
