### ISSUE TITLE
Treatments : Global database of medicines

### ISSUE THREAD

**Issue by anitanagaraj** [integritysystemscompany/animal_schema#33]
Not readily available in any country except by screen scraping. Perhaps MLA could encourage development of some standard APIs atleast for Australia

**Comment by anitanagaraj** [comment]
A related issue is how to make the registered medicine code, batch number and expiry date on physical medicines machine readable. GS1 has a standard for this but it is not widely used.

**Comment by cookeac** [comment]
Formation of a global or even national medicine database is outside of this project scope.
