### ISSUE TITLE
Movement: Arrival: Comment on "agistment" term

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#38]
Agistment isn't a commonly used word outside of Australia and New Zealand. Is there a more international term? We haven't been able to find one in the UK or US.

**Comment by cookeac** [comment]
Agreed, in the UK animals are commonly sent "to/on tack". I did find mention of agistment in one UK science paper in regards to tack.

That said, I also ran these past the ICAR working group and they were ok with the phrase.

**Comment by anitanagaraj** [comment]
Updated the comments for agistment in the spreadsheet
