### ISSUE TITLE
Movement: Arrival: Linking government transactions

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#41]
How are government transactions linked to the iscMovementArrival and iscMovementDeparture events?

An optional government transaction attribute would be useful. That would include the service or country as well as the ID. Perhaps information about the submission as well - success or failure.

**Comment by cookeac** [comment]
Our intent was to capture this with attributes in the Consignment object, which would suggest more attributes should be added to this object.

**Comment by cookeac** [comment]
@anitanagaraj check with Daniel Buchanan and Kerry Johns the transaction ID and status fields that could be added.

**Comment by anitanagaraj** [comment]
@cookeac , discussed with Daniel and I'm thinking of addition this to Consignment object-

governmentTransaction: {
  transactionId: string
  movementId: string,
  status: string (success/fail),
  service: string (e.g. BCMS)
  transactionDate: ‘<date>’
}

**Comment by cookeac** [comment]
@anitanagaraj those fields look sensible to me. I'd suggest we create a new type to hold this - for example **iscTransactionRecordType**. Then add the *transactionRecord* (of type iscTransactionRecordType) to the consignment object. It would seem to me those sort of transaction records could be used elsewhere, hence generalising.
