### ISSUE TITLE
Movement: Death: Clarity on consumption for tax impacts

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#43]
It isn't clear with reason consumption whether that is to be eaten on or off-farm, which can have tax ramifications. Should these be split out?

**Comment by cookeac** [comment]
That could be done - wouldn't want to deal with the tax implications in the animal observation event, but the opportunity to split consumption purpose/location further could be useful for multiple purposes, including biosecurity.

**Comment by cookeac** [comment]
Intention of the disposalMethod enumeration:
- Approved Service - animal died on farm and was disposed of by a service provider
- On Premise - animal died and was buried or cremated on farm
- Consumption - was intended as on-farm consumption (only legal purpose in most countries). Animal was killed for consumption on farm, as opposed to Sold (movement) for off-farm use.

Proposing Consumption to be split as follows
- Consumption On Farm - killed for consumption on farm
- Consumption Off Farm - killed for consumption off farm
