### ISSUE TITLE
Movement: Death: Should disposalReference be required

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#45]
Given the examples for disposalReference, what would a value be for consumption? It doesn't feel like this should be required.

**Comment by sejast** [comment]
disposalReference being mandatory will also discourage people from recording an observed death until the animal has been moved off-farm

**Comment by cookeac** [comment]
I agree, should be optional.

**Comment by anitanagaraj** [comment]
disposalReference is made optional
