### ISSUE TITLE
Movement: Movement Registration: What is the purpose of this record

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#47]
What is the purpose of this record? To record the addition of existing animals into an application? Does that really matter for data interoperability?

In the case of registration, what does induct mean in the comment?  Add to the app or actual induction of animals onto the farm. If it's the later, it would be useful to have a link to the Arrival record. We should also be able to track the government transaction ID.

**Comment by cookeac** [comment]
This mechanism is not just about the transfer of details for an app, but might also include registration of the animal with a formal recording system or a national movement database. Registration is intended to capture the initial registration of an animal, not its movement (arrival/departure). Examples include:
- Animals tagged within ([x] regulatory time period) of birth - application of the tag and induction into whatever official or unofficial recording system is addressed through this event;
- Similarly, existing animals that may have already had tags but are just being formally recorded in (whatever) system for the first time.
