### ISSUE TITLE
Identity Parentage - Confidence indicator

### ISSUE THREAD

**Issue by anitanagaraj** [integritysystemscompany/animal_schema#5]
A confidence indicator for parentage might be useful. Need to check if it is present in farm data standards

**Comment by cookeac** [comment]
Farm Data Standards has:

1. Parentage Method (how the parentage was assessed):

- Observed (e.g. Dam observed giving birth to progeny)
- Associated (e.g. Dam seen feeding progeny)
- Derived (e.g. Sire derived from mating records)
- DNA (the result of a DNA parentage test)

2. DNA Probability (and Reliability) - not specifically defined.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent , Implemented  in the spreadsheet.

**Comment by AndyDe-Aldent** [comment]
Added the parentageAssessedMethod and DNAProbability fields to the JSON
