### ISSUE TITLE
Movement: Organisation: Address type

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#50]
Is there a standard we can use for address? String seems arbitrary and this would be useful as a type.

**Comment by cookeac** [comment]
It would. We just modelled it precisely on schema.org streetAddress. However, a structured type such as schema.org postalAddress might be more appropriate.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent , updated in the spreadsheet

**Comment by AndyDe-Aldent** [comment]
Created the iscPostalAddressType file.
