### ISSUE TITLE
Movement: Person: licence credential isn't specific enough

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#51]
licenseCredential  feels like it should be an array and that each value should have a schema of   license type and license number

**Comment by cookeac** [comment]
@anitanagaraj we decided that we would implement credentials as described above

licenceCredentials: array of [iscLicenceCredentialType]
where iscLicenceCredentialType: allof icarIdentifierType

**Comment by anitanagaraj** [comment]
This has been implemented in the spreadsheet and json files

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent , updated in the spreadsheet

**Comment by AndyDe-Aldent** [comment]
Created the iscLicenceCredentialType file and changed the licenceCredentials field to be of that type.
@anitanagaraj spreadsheet has both "licence" and "license" spellings.   I have set the files to match the spreadsheet but should this be singled down to one spelling?

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent , have changed it to licence with a 'c', which I guess should be used for the noun form.

**Comment by cookeac** [comment]
Updated and simplified - does not need duplicate fields as base icarIdentifierType already has *scheme* and *id*.
