### ISSUE TITLE
Movement: ChangeOfOwnership: 

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#52]
eventMode is a strange name for this field. We would recommend something like "transferEvent". That's not a great name either, but something that describes the data as the type of event held.

**Comment by cookeac** [comment]
**eventMode** was intended to identify the type of event in which the transaction occurred. Alternative names might include:
- eventContext
- withinEvent
- transferEvent
- saleType
etc.

**Comment by anitanagaraj** [comment]
eventMode has now been modified to transferType
