### ISSUE TITLE
Movement: LotDetail: sellingBasis doesn't look very serialization friendly

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#53]
sellingBasis that the value should be serializable. Just PER_HEAD, LIVE_WEIGHT, DRESSED_WEIGHT?

Units shouldn't be included in these values, as not everyone uses metric.

**Comment by cookeac** [comment]
Yes, these were human readible for the purposes of the meeting, but I agree that ideally units should be separate. We had that discussion here too and thought it would be good to canvas opinion at the meeting.

**Comment by cookeac** [comment]
Made the selling basis serialisation friendly and unit free 
- Head
- Liveweight
- CarcaseWeight
- DressedWeight
- Other.
