### ISSUE TITLE
Movement: Lot Assessment: Needs to be complete

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#54]

**Comment by cookeac** [comment]
Agreed, we are hoping to discuss at the meeting.

**Comment by anitanagaraj** [comment]
Feedback from Joel Rockes -Assessment details should be allowed to be entered many times for a given lot - eg an agent could have an assessment, a vendor could have an assessment, a buyer, an accredited assessor/valuer (MLA, Auctions Plus) etc.

**Comment by cookeac** [comment]
Added a very simplified array of uniquely identified assessments with assessment type, value, person responsible, and assessment date.
