### ISSUE TITLE
Movement: TransactionItem: Different items may be of a different unit type

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#55]
Needs the unit type for per head, live weight, dressed, etc as there could be different items could be charged differently in the same transaction.

**Comment by cookeac** [comment]
Linked to #53 - we are keen to discuss people's ideas at the meeting.

**Comment by cookeac** [comment]
Added a *units* field (of type **uncefactMassUnitsType.json**) to **iscTransactionItemType.json**.
