### ISSUE TITLE
Movement: TransactionItem: Discount types

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#56]
Do we need a discount type to handle a fixed amount rather than a percentage?

**Comment by cookeac** [comment]
Good feedback, to discuss at the meeting.

**Comment by cookeac** [comment]
@anitanagaraj we could add an optional discountValue as well as the discount (%) field.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent Updated in the spreadsheet

**Comment by AndyDe-Aldent** [comment]
Added the discountValue property to the JSON schema
