### ISSUE TITLE
Movement: TransactionItem: Do we need to save subtotal?

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#57]
Is subtotal is derived, does it need to be saved? That does make sense in the case where none of the other values are provided.

**Comment by cookeac** [comment]
We discussed the same thing - subTotal does make sense where there is a price that has been agreed by a different method and it is the only field provided.

**Comment by anitanagaraj** [comment]
@AndyDe-Aldent Implemented in the spreadsheet. AndrewDe please check if it has been implemented in the JSON files

**Comment by AndyDe-Aldent** [comment]
the iscTransactionItemType contains an optional Subtotal field.
