### ISSUE TITLE
Movement: Companion documents

### ISSUE THREAD

**Issue by JoelRockes** [integritysystemscompany/animal_schema#62]
The schema seems silent of recording/attaching companion documentation, such as NVD's, Animal Health statements & any other forms of documentation... should this be a consideration?

**Comment by cookeac** [comment]
We've generally taken the view that implementations could extend the core schema to add further optional fields. In this case these might include URLs to documents. 

On the other hand, almost every country has a movement document of some sort, though for many it holds the same information that is already in the **Consignment** object. We could always choose to add a *DocumentURL* (optional, URI string) to the Consignment.
