### ISSUE TITLE
Movement: Handling non-reading tags

### ISSUE THREAD

**Issue by JoelRockes** [integritysystemscompany/animal_schema#64]
In the event where a faulty visual tag is replaced with a new saleyard/Vendor tag (currently handled in NLIS) how would/could/should this be captured here?

**Comment by cookeac** [comment]
I'd suggest there should be a separate animal movements & registrations event for retagging. It would presumably be like the registration event, because the old ID of the animal may or may not be known.

**Comment by cookeac** [comment]
I have added **iscMovementRetagEventResource.json**.
Additional properties:
- *replacementTagType* will vary by country - e.g. red tags in the UK
- *previousIdentifier* previous ID if known and different
- *animalDetail* as for when adding a new animal, if the previous ID is not known, need to provide some details.

@AndyDe-Aldent can you please update the Swagger to include the new event? May also need to address linting if **icarAnimalIdentiferType.json** is not found in repo - I can't see it.
