### ISSUE TITLE
Weigh and Score - Session concept

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#7]
Is there the concept of a session that ties these individual records together? These can be useful to tie multiple observations that were recorded at the same time together.

This could be an optional property.

**Comment by cookeac** [comment]
Yes, I'm keen on this idea as well. We might need to discuss what a minimal set of attributes for a session might be. I have always said these were done at the same time and place, but I note that some devices (TruTest, Gallagher) can add more records to an existing session on a different date. In that case, "session" in that context really just means "file".

**Comment by cookeac** [comment]
We discussed at the meeting, and like the idea of being able to categorise arbitrary sets of events into a "session", which is something like a file or set of related observations.
Suggest: Add a "session" attribute to the event core (string).
This would allow filters to be defined on APIs in the future to return events in a session.

**Comment by anitanagaraj** [comment]
It was decided after the webinar on API model that Rezare will implement a Session object. Hence closing this issue.
