### ISSUE TITLE
Weigh and Score - Required fields?

### ISSUE THREAD

**Issue by sejast** [integritysystemscompany/animal_schema#8]
There aren't any required fields indicated on the weigh or score observations. 

Going from: https://github.com/adewg/ICAR/issues/53, the weight is the only required field, which makes sense.

An update to the spreadsheet would be useful.

**Comment by anitanagaraj** [comment]
Hi Phil,
I have updated the spreadsheet to indicate weight as a mandatory attribute. I will keep this issue open till we discuss any other required fields during the webinar.
